### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')

### ISSUE THREAD

**Issue by NazarXeXe** [YieldRay/soda#1]
Hello. Every time I use the components, this issue occurs.
Stacktrace:
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at /vercel/path0/.next/server/app/page.js:1:32180
    at 3319 (/vercel/path0/.next/server/app/page.js:1:32591)
    at Object.t [as require] (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at require (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:7946)
    at u (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:646)
    at F (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:10477)
    at T (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:8526)
    at rT (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:32387)
    at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63360)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63164)
```
Repo: `https://github.com/NazarXeXe/sodatest`

**Comment by YieldRay** [comment]
Thank you for the report!  
I’ve published `soda-material@0.0.30`, which now supports React 19.  
Feel free to let me know if you encounter any further issues.

**Comment by NazarXeXe** [comment]
I installed the version you provided then countered new issue:
```
ReferenceError: matchMedia is not defined
    at 1213 (/vercel/path0/.next/server/app/page.js:1:48646)
    at Object.t [as require] (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at require (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:7946)
    at u (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:646)
    at F (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:10477)
    at T (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:8526)
    at rT (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:32387)
    at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63360)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63164)
    at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:68946)
```

**Comment by YieldRay** [comment]
> I installed the version you provided then countered new issue:
> 
> ```
> ReferenceError: matchMedia is not defined
>     at 1213 (/vercel/path0/.next/server/app/page.js:1:48646)
>     at Object.t [as require] (/vercel/path0/.next/server/webpack-runtime.js:1:127)
>     at require (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:7946)
>     at u (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:646)
>     at F (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:10477)
>     at T (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:8526)
>     at rT (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:32387)
>     at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63360)
>     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63164)
>     at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:68946)
> ```

Apologies for the inconvenience. I’ve looked into the SSR issue, and `soda-material@0.0.31` should resolve it.

**Comment by NazarXeXe** [comment]
Still the same issue. But importing components individually works (for the client):
```
 ReferenceError: matchMedia is not defined
    at e (../../src/ripple/ripple-color.ts:12:4)
    at eval (../../../src/components/button/Button.tsx:48:62)
  10 |
  11 | export function getReversedRippleColor() {
> 12 |     return matchMedia('(prefers-color-scheme: dark)').matches
     |    ^
  13 |         ? 'rgba(0 0 0 / 0.2)'
  14 |         : 'rgb(255 255 255 / 0.2)'
  15 | } {
  digest: '186623710'
}
```

**Comment by YieldRay** [comment]
> Still the same issue. But importing components individually works (for the client):
> 
> ```
>  ReferenceError: matchMedia is not defined
>     at e (../../src/ripple/ripple-color.ts:12:4)
>     at eval (../../../src/components/button/Button.tsx:48:62)
>   10 |
>   11 | export function getReversedRippleColor() {
> > 12 |     return matchMedia('(prefers-color-scheme: dark)').matches
>      |    ^
>   13 |         ? 'rgba(0 0 0 / 0.2)'
>   14 |         : 'rgb(255 255 255 / 0.2)'
>   15 | } {
>   digest: '186623710'
> }
> ```

You can add the `"use client"` directive at the top of `page.tsx` as a temporary workaround. This issue will be resolved in the next version. Here's an example:

```tsx
"use client";
import "soda-material/dist/style.css";
import { Button } from "soda-material";

export default function Home() {
    return <Button variant="outlined">Button</Button>;
}
```

**Comment by YieldRay** [comment]
I’ve published `soda-material@0.0.32`, now no extra `"use client"` is required by the library itself.  
Thanks again for your report!
